### ISSUE TITLE
DEFAULT fields should be reflected in create* and Shapes

### ISSUE THREAD

**Issue by kennyboy** [mdmoss/doobie-codegen#20]
This could be done with `Default \/ T` or `Option[T]`.

**Comment by mdmoss** [comment]
I've done some research and this is quite tricky.

It seems that JDBC doesn't have a way of representing the `default` atom. This means you can't use something like `INSERT INTO table (col) VALUES (default)`.

It seems the desired outcome could be achieved by:

**\- Omitting the default column from generated `INSERT` statements**

The downside here is that for `n` default-able columns, you get `n^2` inserts depending on what you want default or not.

**\- Runtime query generation**

Not a terrible option, but not really in scope for this project, or

**\- Some kind of special flag (or parsing the default values directly, gulp) indicating what to use as a default.**

This won't work for things like `CURRENT_TIMESTAMP` and other non-value values.

**\- A special flag which says "skip this for insert" or "generate an insert that looks like this".**

Not a terrible option, actually. `-- doobie-codegen: off` has proved useful. I'll investigate further.

**Comment by mdmoss** [comment]
Had a good offline chat with @cmanou and it seems like the happiest option involves:
- No more little pragma-like annotations in schemas. `--doobie-codegen off` seems alright, but let's not go further.
- Adding something to the Generator class that takes some kind of `table -> column -> options` structure.

I think we can resolve the major pain point of this issue with:
- `no-update`, meaning the field will never be included in generated `INSERT` or `UPDATE` statements.
- `scala-default x`, where x is a string that would be used as the default value for the parameter in scala. This might also need some way of forcing imports, but that could come later.

So, for something like a `created_at` field that's defaulted and really shouldn't be written, use the `no-update` option.

For something that has a default that can be expressed in Scala, use a `scala-default` thing.

Otherwise, you have to provide the value. There's maybe a case for a `no-insert` which means the default value for the field would also be used, but I couldn't find an example in my usage where that would be needed.

**Comment by mdmoss** [comment]
We've made an attempt in #22 . Done!
